spring.application.name=KafChat

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.swf8sn9.mongodb.net/kafchat?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

logging.level.root=INFO
logging.level.com.suguru.geto.Kaf=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
spring.mvc.log-request-details=true