spring.application.name=KafChat

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.swf8sn9.mongodb.net/kafchat?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# Logging Configuration
#logging.level.root=INFO
#logging.level.com.suguru.geto.Kaf=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.messaging=DEBUG
#logging.level.org.springframework.web.socket=DEBUG
#spring.mvc.log-request-details=true


# kafka
# --- Kafka connection ---
spring.kafka.bootstrap-servers=localhost:9092

# --- Producer serialization ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Consumer deserialization ---
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.suguru.geto.Kaf.chat.payload
spring.kafka.consumer.auto-offset-reset=latest

# --- The important one: unique group id per JVM instance ---
#Spring Boot's built-in RandomValuePropertySource resolves that placeholder fresh on every JVM start.
spring.kafka.consumer.group-id=kafchat-consumer-${random.uuid}

# --- Topic name, referenced everywhere else instead of a hardcoded string ---
kafka.topic.chat-messages=chat-messages