spring.application.name=KafChat

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.swf8sn9.mongodb.net/kafchat?appName=Cluster0
spring.data.mongodb.auto-index-creation=true